<article class="cq-info-page">
	<section>
		<p>THE INFORMATION CONTAINED IN THIS WEBSITE IS FOR GENERAL INFORMATION PURPOSES ONLY. THE INFORMATION IS PROVIDED BY CLANQUEST.ORG 
			AND WHILE WE ENDEAVOR TO KEEP THE INFORMATION UP TO DATE AND CORRECT, WE MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS 
			OR IMPLIED, ABOUT THE COMPLETENESS, ACCURACY, RELIABILITY, SUITABILITY OR AVAILABILITY WITH RESPECT TO THE WEBSITE OR THE 
			INFORMATION, PRODUCTS, SERVICES, OR RELATED GRAPHICS CONTAINED ON THE WEBSITE FOR ANY PURPOSE. ANY RELIANCE YOU PLACE ON SUCH 
			INFORMATION IS THEREFORE STRICTLY AT YOUR OWN RISK. IN NO EVENT WILL WE BE LIABLE FOR ANY LOSS OR DAMAGE INCLUDING WITHOUT LIMITATION, 
			INDIRECT OR CONSEQUENTIAL LOSS OR DAMAGE, OR ANY LOSS OR DAMAGE WHATSOEVER ARISING FROM LOSS OF DATA OR PROFITS ARISING OUT OF, OR IN 
			CONNECTION WITH, THE USE OF THIS WEBSITE.</p>
		<p>IF A PRODUCT, GOOD OR SERVICE IS ENDORSED BY CLANQUEST.ORG, ANY PAYMENT RECEIVED IN RELATION TO THAT ENDORSEMENT SHALL BE FULLY DISCLOSED.</p>
		<p>THROUGH THIS WEBSITE YOU ARE ABLE TO LINK TO OTHER WEBSITES WHICH ARE NOT UNDER THE CONTROL OF CLANQUEST.ORG. WE HAVE NO CONTROL OVER 
			THE NATURE, CONTENT AND AVAILABILITY OF THOSE SITES. THE INCLUSION OF ANY LINKS DOES NOT NECESSARILY 
			IMPLY A RECOMMENDATION OR ENDORSE THE VIEWS EXPRESSED WITHIN THEM.</p>
		<p>EVERY EFFORT IS MADE TO KEEP THE WEBSITE UP AND RUNNING SMOOTHLY. HOWEVER, CLANQUEST.ORG 
			TAKES NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE FOR, THE WEBSITE BEING TEMPORARILY 
			UNAVAILABLE DUE TO TECHNICAL ISSUES BEYOND OUR CONTROL.</p>
	</section>
</article>
