<article class="cq-info-page">
	<section>
		<p>THIS PRIVACY NOTICE DISCLOSES THE PRIVACY PRACTICES FOR CLANQUEST.ORG. THIS PRIVACY NOTICE APPLIES SOLELY TO INFORMATION COLLECTED BY THIS WEBSITE.</p>
		<h3>INFORMATION COLLECTION, USE, AND SHARING</h3> 
		<p>WE ARE THE SOLE OWNERS OF THE INFORMATION COLLECTED ON THIS SITE. WE ONLY HAVE ACCESS TO/COLLECT INFORMATION THAT YOU VOLUNTARILY GIVE US VIA EMAIL OR OTHER DIRECT CONTACT FROM YOU. WE WILL NOT SELL OR RENT THIS INFORMATION TO ANYONE.
		WE WILL USE YOUR INFORMATION TO RESPOND TO YOU, REGARDING THE REASON YOU CONTACTED US. WE WILL NOT SHARE YOUR INFORMATION WITH ANY THIRD PARTY OUTSIDE OF OUR ORGANIZATION, OTHER THAN AS NECESSARY TO FULFILL YOUR REQUEST, E.G. TO SHIP AN ORDER.
		UNLESS YOU ASK US NOT TO, WE MAY CONTACT YOU VIA EMAIL IN THE FUTURE TO TELL YOU ABOUT SPECIALS, NEW PRODUCTS OR SERVICES, OR CHANGES TO THIS PRIVACY POLICY.</p>
		<h3>YOUR ACCESS TO AND CONTROL OVER INFORMATION</h3> 
		<p>YOU MAY OPT OUT OF ANY FUTURE CONTACTS FROM US AT ANY TIME. YOU CAN DO THE FOLLOWING AT ANY TIME BY CONTACTING US VIA THE EMAIL ADDRESS OR PHONE NUMBER GIVEN ON OUR WEBSITE:</p>
		<ul>
		<li>SEE WHAT DATA WE HAVE ABOUT YOU, IF ANY.</li>
		<li>CHANGE/CORRECT ANY DATA WE HAVE ABOUT YOU.</li>
		<li>HAVE US DELETE ANY DATA WE HAVE ABOUT YOU.</li>
		<li>EXPRESS ANY CONCERN YOU HAVE ABOUT OUR USE OF YOUR DATA.</li>
		</ul>
		<h3>SECURITY</h3> 
		<p>WE TAKE PRECAUTIONS TO PROTECT YOUR INFORMATION. WHEN YOU SUBMIT SENSITIVE INFORMATION VIA THE WEBSITE, YOUR INFORMATION IS PROTECTED BOTH ONLINE AND OFFLINE.</p>
		<p>WHEREVER WE COLLECT SENSITIVE INFORMATION (SUCH AS CREDIT CARD DATA), THAT INFORMATION IS ENCRYPTED AND TRANSMITTED TO US IN A SECURE WAY. YOU CAN VERIFY THIS BY LOOKING FOR A LOCK ICON IN THE ADDRESS BAR AND LOOKING FOR "HTTPS" AT THE BEGINNING OF THE ADDRESS OF THE WEB PAGE.
		WHILE WE USE ENCRYPTION TO PROTECT SENSITIVE INFORMATION TRANSMITTED ONLINE, WE ALSO PROTECT YOUR INFORMATION OFFLINE. ONLY EMPLOYEES WHO NEED THE INFORMATION TO PERFORM A SPECIFIC JOB (FOR EXAMPLE, BILLING OR CUSTOMER SERVICE) ARE GRANTED ACCESS TO PERSONALLY IDENTIFIABLE INFORMATION. THE COMPUTERS/SERVERS IN WHICH WE STORE PERSONALLY IDENTIFIABLE INFORMATION ARE KEPT IN A SECURE ENVIRONMENT.</p>
		<h3>COOKIES</h3>
		<p>WE USE "COOKIES" ON THIS SITE. A COOKIE IS A PIECE OF DATA STORED ON A SITE VISITOR'S HARD DRIVE TO HELP US IMPROVE YOUR ACCESS TO OUR SITE AND IDENTIFY REPEAT VISITORS TO OUR SITE. FOR INSTANCE, WHEN WE USE A COOKIE TO IDENTIFY YOU, YOU WOULD NOT HAVE TO LOG IN A PASSWORD MORE THAN ONCE, THEREBY SAVING TIME WHILE ON OUR SITE. COOKIES CAN ALSO ENABLE US TO TRACK AND TARGET THE INTERESTS OF OUR USERS TO ENHANCE THE EXPERIENCE ON OUR SITE. USAGE OF A COOKIE IS IN NO WAY LINKED TO ANY PERSONALLY IDENTIFIABLE INFORMATION ON OUR SITE.
		</p><p>SOME OF OUR BUSINESS PARTNERS MAY USE COOKIES ON OUR SITE (FOR EXAMPLE, ADVERTISERS). HOWEVER, WE HAVE NO ACCESS TO OR CONTROL OVER THESE COOKIES.</p>
		<h3>SURVEYS &amp; CONTESTS</h3>
		<p>FROM TIME-TO-TIME OUR SITE REQUESTS INFORMATION VIA SURVEYS OR CONTESTS. PARTICIPATION IN THESE SURVEYS OR CONTESTS IS COMPLETELY VOLUNTARY AND YOU MAY CHOOSE WHETHER OR NOT TO PARTICIPATE AND THEREFORE DISCLOSE THIS INFORMATION. INFORMATION REQUESTED MAY INCLUDE CONTACT INFORMATION (SUCH AS NAME AND SHIPPING ADDRESS), AND DEMOGRAPHIC INFORMATION (SUCH AS ZIP CODE, AGE LEVEL). CONTACT INFORMATION WILL BE USED TO NOTIFY THE WINNERS AND AWARD PRIZES. SURVEY INFORMATION WILL BE USED FOR PURPOSES OF MONITORING OR IMPROVING THE USE AND SATISFACTION OF THIS SITE.</p>
		<h3>SHARING</h3>
		<p>WE PARTNER WITH ANOTHER PARTY TO PROVIDE SPECIFIC SERVICES. WHEN THE USER SIGNS UP FOR THESE SERVICES, WE WILL SHARE NAMES, OR OTHER CONTACT INFORMATION THAT IS NECESSARY FOR THE THIRD PARTY TO PROVIDE THESE SERVICES. THESE PARTIES ARE NOT ALLOWED TO USE PERSONALLY IDENTIFIABLE INFORMATION EXCEPT FOR THE PURPOSE OF PROVIDING THESE SERVICES.</p>
		<p>WE USE AN OUTSIDE SHIPPING COMPANY TO SHIP ORDERS, AND A CREDIT CARD PROCESSING COMPANY TO BILL USERS FOR GOODS AND SERVICES. THESE COMPANIES DO NOT RETAIN, SHARE, STORE OR USE PERSONALLY IDENTIFIABLE INFORMATION FOR ANY SECONDARY PURPOSES BEYOND FILLING YOUR ORDER.</p>
		<h3>LINKS</h3> 
		<p>THIS WEBSITE CONTAINS LINKS TO OTHER SITES. PLEASE BE AWARE THAT WE ARE NOT RESPONSIBLE FOR THE CONTENT OR PRIVACY PRACTICES OF SUCH OTHER SITES. WE ENCOURAGE OUR USERS TO BE AWARE WHEN THEY LEAVE OUR SITE AND TO READ THE PRIVACY STATEMENTS OF ANY OTHER SITE THAT COLLECTS PERSONALLY IDENTIFIABLE INFORMATION.</p>
		<h3>DISCREPANCY</h3>
		<p>IF YOU FEEL THAT WE ARE NOT ABIDING BY THIS PRIVACY POLICY, YOU SHOULD CONTACT US IMMEDIATELY VIA TELEPHONE AT +1-330-608-7800 OR VIA ADMIN@CLANQUEST.ORG.</p>
	</section>
</article>
